// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxhSPkpLPZMmoY14fr2MktDpSCb4LHjg',
    appId: '1:884118690450:web:95982d6e671d477e1ce44b',
    messagingSenderId: '884118690450',
    projectId: 'harmonyhub-27244',
    authDomain: 'harmonyhub-27244.firebaseapp.com',
    storageBucket: 'harmonyhub-27244.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5waRg1_Mx7V5iOjJDsgtXW1wKutyWB6A',
    appId: '1:884118690450:android:41e304b27145214d1ce44b',
    messagingSenderId: '884118690450',
    projectId: 'harmonyhub-27244',
    storageBucket: 'harmonyhub-27244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBC-3QXirKO6K8eITQtf4bKbVSffY6onM',
    appId: '1:884118690450:ios:6f621dfc6106e4101ce44b',
    messagingSenderId: '884118690450',
    projectId: 'harmonyhub-27244',
    storageBucket: 'harmonyhub-27244.firebasestorage.app',
    iosBundleId: 'com.example.harmonyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBC-3QXirKO6K8eITQtf4bKbVSffY6onM',
    appId: '1:884118690450:ios:6f621dfc6106e4101ce44b',
    messagingSenderId: '884118690450',
    projectId: 'harmonyhub-27244',
    storageBucket: 'harmonyhub-27244.firebasestorage.app',
    iosBundleId: 'com.example.harmonyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzxhSPkpLPZMmoY14fr2MktDpSCb4LHjg',
    appId: '1:884118690450:web:d06d9b314ed1a0c11ce44b',
    messagingSenderId: '884118690450',
    projectId: 'harmonyhub-27244',
    authDomain: 'harmonyhub-27244.firebaseapp.com',
    storageBucket: 'harmonyhub-27244.firebasestorage.app',
  );
}
